### ISSUE TITLE
Unixtime bug. Trækker ikke system_time_at_ntp fra

### ISSUE THREAD

**Issue by sloev** [nabovarme/MeterLogger#12]
Vi har en kæmpe fejl. Vi gemmer ikke et nulpunkt som vi kan trække fra. I praksis skal vi i "setunix" gemme ey nul=systemgettime og i getunix skal den så trække nul fra system_time og ligge det til systemgettime samt unixtime. Ellers tæller vi systemgettime fra sidste setunix time med i alle fremtidige getunixtime

**Comment by st0ff3r** [comment]
tror jeg gør i den seneste  version

**Comment by sloev** [comment]
fixed
