### ISSUE TITLE
brug json! (eller protobuf)

### ISSUE THREAD

**Issue by sloev** [nabovarme/MeterLogger#13]
vi skal ikke sende:

/kamstrup_id/unixtime/flow_ud 30
/kamstrup_id/unixtime/flow_ind 30
/kamstrup_id/unixtime/temp 100

i stedet skal enten:

message = "{"unixtime": 120324567, "flow ud": 30, "flow ind": 30, "temp": 100}"
messagebytes = message.getbytes()

/kamstrup_id messagebytes

eller:

/kamstrup_id/unixtime messagebytes

DET skal siges at der i den anden ende er en simpel:
bytes = receivedbytes
jsondict = json.dump(bytes)
unixtime = jsondict["unixtime"]
flowud = jsondict["flow ud"]
flowind = jsomdict["flow ind"]

**Comment by sloev** [comment]
husk json er enormt standar og bortser fra json-to-bytes og bytes-to-json er indholdet jo aschii og nemt for os at læse :-)

**Comment by sloev** [comment]
man kunne dog også bruge googles protobuf.
https://mobilebit.wordpress.com/2013/09/25/protobuf-mqtt-yummy-fast/

sammenligning mellem json og protobuf:
JSON

·       human readable/editable

·       can be parsed without knowing schema in advance

·       excellent browser support

·       less verbose than XML (relatively small on the wire)

Protobuf

·       very dense data (very small on the wire)

·       hard to robustly decode without knowing the schema (data format is internally ambiguous, and needs schema to clarify)

·       very fast processing

·       not intended for human eyes (dense binary)

Protocol buffers

Protocol buffers are binary and quite compact. You can immediately use the data you’ve received by just pointing to the right portions of a buffer (“zero-copy”), after a very light parsing. If you pass a lot of numbers, it may be quite noticeable. Zero-copy makes most sense for C or C++ code, though; in Java, Python, etc numbers and strings will probably change representation to fit the language.

JSON

JSON is a textual format. It is easy to parse efficiently, and you can even have zero-copy strings, but everything else should be parsed. JSON may become wasteful if you pass a lot of mappings with the same keys ([{“foo”:1, “bar”:2}, {“foo”:3, “bar”:4}]), but compression before transmission (mod_gzip, etc) may eliminate this problem.

**Comment by sloev** [comment]
konklusion:
protobuf har vist indbygget komprimering til gengæld er den ulæselig for mennesker

vi har ikke data nok til at gøre det ulæseligt for mennesker.
json all the way!!!

**Comment by sloev** [comment]
p://m2mgo.com/Dev/Mqtt

M2MGO supports two common data payload formats Key/Value pairs and JSON format
        • Key/Value pair: The Key/Value pair has following structure
key=value
Example:temperature=25
The Key/Value pairs can be combined
key1=value1&key2=value2&key3=value3

JSON: The JSON format has following structure:
[
{"key1":"value1"},
{"key2":"value2"},
{"key3":"value3"},
]

**Comment by st0ff3r** [comment]
> On 10/03/2015, at 12.30, johannes jorgensen notifications@github.com wrote:
> 
> p://m2mgo.com/Dev/Mqtt
> 
> M2MGO supports two common data payload formats Key/Value pairs and JSON format
>         • Key/Value pair: The Key/Value pair has following structure
> key=value
> Example:temperature=25
> The Key/Value pairs can be combined
> key1=value1&key2=value2&key3=value3
> 
> JSON: The JSON format has following structure:
> [
> {"key1":"value1"},
> {"key2":"value2"},
> {"key3":"value3"},
> ]
> 
> —
> Reply to this email directly or view it on GitHub.

sådan komprimerer man:

size_t compressHeatshrink(char *in, int insize, char *out, int outsize, int level) {
    char *inp=in;
    char *outp=out;
    size_t len;
    int ws[]={5, 6, 8, 11, 13};
    int ls[]={3, 3, 4, 4, 4};
    HSE_poll_res pres;
    HSE_sink_res sres;
    size_t r;
    if (level==-1) level=8;
    level=(level-1)/2; //level is now 0, 1, 2, 3, 4
    heatshrink_encoder *enc=heatshrink_encoder_alloc(ws[level], ls[level]);
    if (enc==NULL) {
        perror("allocating mem for heatshrink");
        exit(1);
    }
    //Save encoder parms as first byte
    *outp=(ws[level]<<4)|ls[level];
    outp++; outsize--;

```
r=1;
do {
    if (insize>0) {
        sres=heatshrink_encoder_sink(enc, inp, insize, &len);
        if (sres!=HSER_SINK_OK) break;
        inp+=len; insize-=len;
        if (insize==0) heatshrink_encoder_finish(enc);
    }
    do {
        pres=heatshrink_encoder_poll(enc, outp, outsize, &len);
        if (pres!=HSER_POLL_MORE && pres!=HSER_POLL_EMPTY) break;
        outp+=len; outsize-=len;
        r+=len;
    } while (pres==HSER_POLL_MORE);
} while (insize!=0);

if (insize!=0) {
    fprintf(stderr, "Heatshrink: Bug? insize is still %d. sres=%d pres=%d\n", insize, sres, pres);
    exit(1);
}

heatshrink_encoder_free(enc);
return r;
```

}

https://github.com/nabovarme/kamstrup-wifi/blob/master/mkespfsimage/main.c

så skal der bare implementeres udpakning i meter_grapher.pl, men det er LZSS...

**Comment by sloev** [comment]
vi bruger get formatering som i:
/sample/kamstrupserienummer/unixtime t1=50&t2=70&m4=100
forklaring:
at vi bruger http-get formatering i value linjen samt at man kan kategorisere topics efter kamstrup serienummer samt unixtime
