### ISSUE TITLE
soft ap gem credentials

### ISSUE THREAD

**Issue by sloev** [nabovarme/MeterLogger#19]
så længe du holder dig til 12 tegn (minimum?) kan du lave hvilket som helst password på dit softap
ssid er ikke udforsket endnu

der er et bug i usermain.c 
når man via http config specificerer hvilket ap den skal koble på. kobler den sig på fint. Men når config mode timer ud og den skal loade sin wifi config er det stadig den gamle. http config formpr altså ikke at gemme credentials

**Comment by st0ff3r** [comment]
stadig bug der gør at man ikke kan skifte fra netværk med adgangskode tilbage til åbent netværk?

**Comment by st0ff3r** [comment]
ingen bug aligevel
