### ISSUE TITLE
watchdog timer, hvad?

### ISSUE THREAD

**Issue by sloev** [nabovarme/MeterLogger#3]
kan man bruge en watchdog timer til at sørge for at den rebooter hvis der sker en fejl.

watchdog er hardware og kan bindes på en variable i userland som udfra et kriteria kan auto reboote

hvilke fejl kunne være interessante at reboote ude fra?

**Comment by st0ff3r** [comment]
hvis mqtt -> reset watchdog timer

**Comment by st0ff3r** [comment]
done in branch watchdog
