### ISSUE TITLE
mesh

### ISSUE THREAD

**Issue by st0ff3r** [nabovarme/MeterLogger#34]

**Comment by sloev** [comment]
https://github.com/espressif/ESP8266_MESH_DEMO

**Comment by st0ff3r** [comment]
> On 24. mar. 2016, at 18.07, johannes jorgensen notifications@github.com wrote:
> 
> https://github.com/espressif/ESP8266_MESH_DEMO

jeps har kigget lidt på det, men det kræver et setup med flere før jeg kan teste...

**Comment by st0ff3r** [comment]
done via wifi router config (AP=1) in mesh branch
