### ISSUE TITLE
kan man kommunikere/flashe med esp igennem kamstrup ir seriel?

### ISSUE THREAD

**Issue by sloev** [nabovarme/MeterLogger#4]
ja de er interconnected!

hvordan skulle det ske med de ch_pd og gpio 0 der jo skal forbindes til gnd og vcc i progrmamer mode?
løsningsforslag:
brug en reedswitch så når man skal programme gør man:
1: sæt meterlogger til ir på kamstrup
2: sæt magnet på hemmeligt sted (foresager at ch_pd og gpio0 forbindes til programmer mode)
3: start flash (i 1200bps tror jeg)

**Comment by st0ff3r** [comment]
kommer til at tage en krig - app.out fylder 836KB nu
